### ISSUE TITLE
Assertion error while converting WADL to Swagger 2

### ISSUE THREAD

**Issue by hiveship** [lucybot/api-spec-converter#72]
I am getting an assertion error while trying to convert a WADL source file to it's Swagger 2 representation.

The stack trace is :

    at convertType (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:56:5)
    at convertParameter (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:107:19)
    at arrayMap (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1406:25)
    at Function.map (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:6710:14)
    at convertMethod (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:146:29)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:165:30
    at arrayEach (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:3345:13)
    at convertResource (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:163:7)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:184:20

And in the code, it seems to be linked to XSDfiles ```( assert(wadlType.indexOf('xsd:') === 0);```). I don't really understand that.. Can you give me some more information ?

**Comment by IvanGoncharov** [comment]
@hiveship `assert(wadlType.indexOf('xsd:') === 0);` checks that typename starts with `xsd:` prefix.
Can you share your WADL file?

Currently WADL conversation isn't mature. We basically tested it only with WADL specs used in Apigee consoles. But you can help by reporting issues with it and we will try to fix it ASAP.

**Comment by hiveship** [comment]
Here is my WADL file, I think it is valid since it can be computed by the
Maven plugin "WADL to JAVA" and generate a client SDK.
I do not provide all the .xsd imports, I don't think thaty
"api-spec-converters" need them to process conversion ?




2015-12-21 14:28 GMT+01:00 Ivan Goncharov <notifications@github.com>:

> @hiveship <https://github.com/hiveship> assert(wadlType.indexOf('xsd:')
> === 0); checks that typename starts with xsd: prefix.
> Can you share your WADL file?
>
> Currently WADL conversation isn't mature. We basically tested it only with
> WADL specs used in Apigee consoles. But you can help by reporting issues
> with it and we will try to fix it ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucybot/api-spec-converter/issues/72#issuecomment-166305515>
> .
>



-- 

*Maëlig NANTEL*
Mobile : +33 (0)6 69 47 39 00
Mail : *maelig.nantel@gmail.com <maelig.nantel@gmail.com>*

**Comment by IvanGoncharov** [comment]
@hiveship I don't see your attachment, can you submit it through Github(preferred) or send to `ivan.goncharov.ua@gmail.com`

**Comment by IvanGoncharov** [comment]
@hiveship (y) I recieved it. I will take a look and post results here.

**Comment by IvanGoncharov** [comment]
@hiveship Problem that in your WADL file XML Schema assigned to `xs` namespace and we expect it to be `xsd`. It's incorrect assumption and I will try to fix it in a day or two.

**Comment by IvanGoncharov** [comment]
@hiveship Merry christmas :christmas_tree: :santa: 
Sorry for delay, I fixed first bug and will commit fix today.
But I discover couple more that block conversion of your WADL example.
I will continue to work on it.

Your example is also will be good addition for our testsuite.
Can I commit it to this repository and make it public?

**Comment by hiveship** [comment]
I don't thnk it's a good idea to make it public since there is my company
name on it. I can try to modify it to remove my company name nnext weekd if
it's ok for you.
Merry christmas :)

2015-12-25 22:24 GMT+01:00 Ivan Goncharov <notifications@github.com>:

> @hiveship <https://github.com/hiveship> Merry christmas [image:
> :christmas_tree:] [image: :santa:]
> Sorry for delay, I fixed first bug and will commit fix today.
> But I discover couple more that block conversion of your WADL example.
> I will continue to work on it.
>
> Your example is also will be good addition for our testsuite.
> Can I commit it to this repository and make it public?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucybot/api-spec-converter/issues/72#issuecomment-167263063>
> .
>



-- 

*Maëlig NANTEL*
Mobile : +33 (0)6 69 47 39 00
Mail : *maelig.nantel@gmail.com <maelig.nantel@gmail.com>*

**Comment by IvanGoncharov** [comment]
> I can try to modify it to remove my company name nnext weekd if
it's ok for you.

@hiveship Yes, definitely.

**Comment by IvanGoncharov** [comment]
@hiveship Can you please try `1.6.1` release.
Note: we still missing response conversion.

**Comment by hiveship** [comment]
I have installed "api-spec-converter" using npm install and then run the tool using my command line. I'm new with node js. How can I swtich to 1.6.1 release ?

I will edit the wadl and sent it to you today.

**Comment by IvanGoncharov** [comment]
@hiveship NPM should have `1.6.1` version so you just need to run `npm install api-spec-converter` one more time. If it doesn't help, please post error output here.

> I will edit the wadl and sent it to you today.

Thank you.

**Comment by hiveship** [comment]
While trying with the same WADL I still got an error:
```
mnantel@mnantel-VirtualBox:~/Bureau$ api-spec-converter foo.wadl --from=wadl --to=swagger_2
AssertionError: Error during convertion: false == true
    at convertType (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:56:5)
    at convertParameter (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:107:19)
    at arrayMap (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1406:25)
    at Function.map (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:6710:14)
    at convertMethod (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:146:29)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:165:30
    at arrayEach (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:3345:13)
    at convertResource (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:163:7)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:184:20
````

I have also tried with a simpler WADL file and got another error:

```
mnantel@mnantel-VirtualBox:~/Bureau$ api-spec-converter WADLExample.xml --from=wadl --to=swagger_2
AssertionError: Error during convertion: false == true
    at convertResource (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:159:5)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:184:20
    at arrayEach (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:3345:13)
    at convertToSwagger (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:182:5)
    at converters.swagger_2 (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:18:22)
    at BaseType.convertTo (/usr/local/lib/node_modules/api-spec-converter/lib/base-type.js:122:3)
    at /usr/local/lib/node_modules/api-spec-converter/index.js:37:14
    at /usr/local/lib/node_modules/api-spec-converter/index.js:17:7
    at null.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/lib/base-type.js:109:7)
[WADLExample.txt](https://github.com/lucybot/api-spec-converter/files/77259/WADLExample.txt)


```
Attachment: the 2nd WADL. I can provide the XSD models files if needed

**Comment by IvanGoncharov** [comment]
@hiveship can you please check version: `api-spec-converter --version`.
From your command line it's looks like you install it globally so to update you need to add `-g` flag.
`npm install -g api-spec-converter`

> I can provide the XSD models files if needed

Currently we don't do response conversion, but it will be very useful in future.

**Comment by hiveship** [comment]
Sorry, my mistake I was not on version 1.6.1.
It seems to be ok with the original WADL file, no error while converting. I imported the generated JSON to Swagger Editor, and I got a little error, missing an element "info". You can solve the error just by adding at the beginning of your JSON output:
```
    "info": {
        "title": "< An API title here >",
        "description": "< An API description here >",
        "version": "< a version here >"
    },
```
I think you can leave empty strings if those information are not provided in the WADL file.
First attachment: an edited version of this WADL, you can make it public (not realy human-friendly for reading, sorry :/)
[FakeAPI.txt](https://github.com/lucybot/api-spec-converter/files/77300/FakeAPI.txt)



However, I also tested with my simpler example, and I got another error:
```
mnantel@mnantel-VirtualBox:~/Bureau$ api-spec-converter WADLExample.xml --from=wadl --to=swagger_2 > result_WADLExample.txt
AssertionError: Error during convertion: null == true
    at convertType (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:61:5)
    at convertParameter (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:120:19)
    at arrayMap (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1406:25)
    at Function.map (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:6710:14)
    at convertResource (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:177:30)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:190:22
    at arrayEach (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/node_modules/lodash/index.js:3345:13)
    at convertResource (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:189:7)
    at /usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:190:22
```
The attachment:
[WADLExample.txt](https://github.com/lucybot/api-spec-converter/files/77283/WADLExample.txt)
You also can make it public :)

**Comment by IvanGoncharov** [comment]
@hiveship I fixed WADL error and also added your test case.
Please retest?

**Comment by IvanGoncharov** [comment]
@hiveship Can you please retest?

**Comment by hiveship** [comment]
@IvanGoncharov Yes sorry, totally missed. 
I just updated my version of the api spec converter via ```sudo npm install -g api-spec-converter``` and retest.

Seems good. However, the "info" element still missing, and generate an error in the Swagger Editor / Swagger UI components. (The error is not visible during the api-spec-converter execution).

Add the following, for each generation, at the begining of the Swagger JSON file:
```json
    "info": {
        "title": "< An API title here >",
        "description": "< An API description here >",
        "version": "< a version here >"
    },
````

**Comment by annegentle** [comment]
I have an error when testing conversion of WADL to Swagger_2 as well. 

```$ api-spec-converter api-ref/target/docbkx/html/wadls/identity.wadl --from=wadl --to=swagger_2 > swagger/identity-swagger.json
TypeError: Error during convertion: Cannot read property 'resources' of undefined
    at convertToSwagger (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:224:42)
    at converters.swagger_2 (/usr/local/lib/node_modules/api-spec-converter/lib/types/wadl.js:18:22)
    at BaseType.convertTo (/usr/local/lib/node_modules/api-spec-converter/lib/base-type.js:130:3)
    at /usr/local/lib/node_modules/api-spec-converter/index.js:37:14
    at /usr/local/lib/node_modules/api-spec-converter/index.js:17:7
    at null.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/lib/base-type.js:117:7)
    at null.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/lib/base-type.js:47:7)
    at /usr/local/lib/node_modules/api-spec-converter/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/api-spec-converter/node_modules/async/lib/async.js:361:13
    at /usr/local/lib/node_modules/api-spec-converter/node_modules/async/lib/async.js:52:16
```
Same happens for another WADL from the collection I'm using from https://github.com/openstack/api-site/tree/master/api-ref/src/wadls where all the entity references are resolved after building.

Here's an attachment of an example one with this error. See what you think! Thanks.
[identity.txt](https://github.com/lucybot/api-spec-converter/files/120594/identity.txt)

**Comment by IvanGoncharov** [comment]
@annegentle Thank you for such detailed bug report, it really simplified my work.
It's really hard to properly implement XML namespaces in JS :cry: 
Especially since we provide browser version of our tool and can't use binary libraries under the hood.
So I implemented striping of prefixes from tag and attribute names.
Can you please test it with `npm install -g lucybot/api-spec-converter`?

**Comment by annegentle** [comment]
Thanks, works fine now, except the Swagger Editor wants an "info" section, which we've filled in with something like this, based on a WADL for an Image API:

```"info": {
    "license": {
      "name": "Apache 2.0", 
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }, 
    "title": "Image service", 
    "version": "v1", 
    "x-service": "image"
  }, 
```

In our case, we can hard-code the license info, understandable that you can't for your tool. Still, you can probably extract at least the title and version. Just a thought for further enhancement for WADL <> Swagger 2.0. Appreciate the quick look!

**Comment by IvanGoncharov** [comment]
@annegentle 
> Still, you can probably extract at least the title and version.

I searched both in WADL spec and in OpenStack WADL files and I can't find `title` and `version`.
Can you please post link to WADL with such fields?

**Comment by IvanGoncharov** [comment]
@hiveship 
> Add the following, for each generation, at the begining of the Swagger JSON file:
```json
    "info": {
        "title": "< An API title here >",
        "description": "< An API description here >",
        "version": "< a version here >"
    },
````

Thank you for suggestion, it took me some time but I implemented it in `1.9.0` release.
It disable by default, to enable just add `-d` flag.
I choose to only add `title` and `version`, but not `description` because it not mandatory field in Swagger 2.0.

**Comment by IvanGoncharov** [comment]
> > Still, you can probably extract at least the title and version.
> 
> I searched both in WADL spec and in OpenStack WADL files and I can't find `title` and `version`.
> Can you please post link to WADL with such fields?
> 

@annegentle If you can please answer my previous question.
It will help us to improve this tool.
